### ISSUE TITLE
plain himself

### ISSUE THREAD

**Issue by dudenoob34** [dudenoob34/dudes-game-hub#1]
plain is hoenstly like really fucking annoying dudfe like jesus fucking christ he published a game called polyheck 2 and then I tried to stea- I mean uhhhhhhhhhhhhhhhhh save the game ut then like he deleted it so I'm sad oh so very sad yeah anyways um I don't know how to uh get the game and plain wont give me the files so I'm like pretty FUCKING SAD WAAAAAAAAAAA

**Comment by PlainSys** [comment]
Wow

**Comment by dudenoob34** [comment]
> 

lol

**Comment by PlainSys** [comment]
its been months, this dude couldve got the PolyHeck 2 files had he simply accepted my offer of simply giving it to him.
